name: test
on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:

      - name: ECHO ECHO
        run: |
          echo "${{ github.run_number }}"
          echo "$GITHUB_RUN_ATTEMPT" || echo ${{ github.run_attempt }}
          echo ${{ github.run_attempt }}

